name: Delete caches

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cache-deletion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Delete existing nx cache
        run: |
          filename="cache-list"
          gh extension install actions/gh-actions-cache
          gh actions-cache list > cache-list
          while IFS= read -r line; do

            set -- $line

            cache-name=$1
            gh actions-cache delete $cache-name --confirm || true


          done < "$filename"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
