name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

permissions:
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: test_artifacts
          path: ./build_test
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - run: |
          ls
          ls ./build_test
          for DIR in "./build"/*/; do
            if [ -d "$DIR" ]; then
                npm publish $DIR/*.tgz
            fi
          done
        name: Publish NPM modules
        if: ${{ hashFiles('./build') != '' }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
