name: CD
run-name: ${{ github.event_name }}
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

permissions:
  actions: write

jobs:
  check:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - run: |
          count=$(ls -1 "$DIRECTORY"/*.tgz 2>/dev/null | wc -l)
          echo "There are $count .tgz files in the directory."
        name: count things to publish

  publish:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - run: |
          for FILE in ./build/*.tgz; do
            if [ -e "$FILE" ]; then
                npm publish $FILE
            fi
          done
        name: Publish NPM modules
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
