name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

permissions:
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - run: |
          for DIR in "./build"/*/; do
            if [ -d "$DIR" ]; then
                echo "Processing directory: $DIR"
                ls "$DIR"
            fi
          done
      # - name: Extract package name from tag
      #   id: extract_package_name
      #   run: |
      #     tag=${{ github.ref_name }}
      #     package_name=$(echo "$tag" | cut -d'@' -f1)
      #     package_version=$(echo "$tag" | cut -d'@' -f2)
      #     echo "package_name=$package_name" >> "$GITHUB_ENV"
      #     echo "package_version=$package_version" >> "$GITHUB_ENV"

      # - run: npm publish ./build/$package_name/$package_name-$package_version.tgz --dry-run
      #   name: Publish to NPM
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
