name: publish test

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build
