name: Tags since

on:
  push:
    branches: [main, feature/*]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.test.outputs.matrix }}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: git tag testtag123
      - run: git describe --tags

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.CONTINUOUS_DEPLOYMENT }}
        run: |
          git push --tags