name: Test and build

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x, 21.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - run: git checkout main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: npm-${{ matrix.node-version }}-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile

      - name: Cache npm dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: npm-${{ matrix.node-version }}-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Derive appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "main"
          error-on-no-successful-workflow: true

      - run: pnpm nx affected -t prettier:check
      - run: pnpm nx affected -t lint:check
      - run: pnpm nx affected -t test
      - run: pnpm nx affected -t build
