name: test-deploy

on:
  workflow_run:
    workflows: [CI-CD]
    types:
      - completed

permissions:
  actions: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - run: echo "in here"